### PR TITLE
Add Automatic CFG & Jank HiDiffusion toggles

### PR DESCRIPTION
**Pull request by StylusEcho**
## Description

* Adds master toggles for the two above extensions, allowing to completely turn them on or off independent of the individual features on the tabs of those extensions.
For users of Tab Extension, this allows toggling these extensions with a ctrl-left click.

## Screenshots/videos:
Screenshot 2024-08-01 215301
Screenshot 2024-08-01 215327

## Checklist:

- [x] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [x] I have performed a self-review of my own code
- [x] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [ ] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)
Sorry, this is my first ever pull request on Github. I tried to run the tests and it seems like reForge doesn't like loading the test checkpoint (empty.pt), so the test fails...

### CODE REVIEW

**Comment by StylusEcho** [comment]
Hmm, this might need some further testing, give me a day or so.

**Comment by Panchovix** [comment]
By the way did some updates on raunet_script.py, if you want to check.

**Comment by StylusEcho** [comment]
Yeah, saw that. I'll wait until the HiDiffusion bugs get sorted and review this again.

**Comment by Panchovix** [comment]
It should be fixed now I think? Or did you notice an issue?

**Pull request closed without merging**
