### PR TITLE
Add builtin extension "APG_ImYourCFGNow"

### PR DESCRIPTION
**Pull request by Ristellise**
# The APG has wololo'd into your CFG!

## Description

* This implementation is based off from here https://github.com/MythicalChu/ComfyUI-APG_ImYourCFGNow
* Most of the node code is exactly the same from MythicalChu. Bless his soul.
* Only stuff I did is hook up the code to the extensions by referencing from rescaleCFG extension

## Screenshots/videos:

**APG (Default Settings)**

image

**CFG (CFG 7, Defaults)**

image

Notes about screenshot:

- adetailer was used in the original and the APG version to give a more accurate of "What you can expect".
- Consider experimenting with the 4 sliders. I believe the defaults are for **SDXL**. Which may not be so great for _SD 1.5 models._

## Misc

when writing out to a png file, the following args are included:
```py
args = {
    "apgisyourcfg_enabled": True,
    "apgisyourcfg_scale": self.apg_scale,
    "apgisyourcfg_momentum": self.apg_moment,
    "apgisyourcfg_norm_thr": self.apg_norm_thr,
    "apgisyourcfg_eta": self.apg_eta,
}
```

If debug logging is enabled, you will see a `WOLOLO: \"APG is now your CFG!\"`. This is normal.

## Checklist:

- [x] I have read [contributing wiki page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing)
- [x] I have performed a self-review of my own code
- [x] My code follows the [style guidelines](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing#code-style)
- [x] My code passes [tests](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Tests)

### CODE REVIEW

**Comment by jhlchu** [comment]
Is there any reason why APG would be giving me kind of mushy washed-out images?
|APG|No APG|
|-|-|
|||

CFG: 2
Scale: 2
Momentum: -0.05
Threshold: 3
Eta: 1

Tried it on `main` and `dev_upstream` with two different XL checkpoints. Reset my configs to a fresh one from reForge, but overall can't seem to get APG working like in the sample.

**Comment by Zotikus1001** [comment]
I've also been having a bit of issues with APG.

I noticed the comfy node got updated with some fixes, could you also update this one?

Also, are we supposed to adjust the normal cfg as well while using apg? Im a bit confused on this.
I see 0.001% difference on the results with APG on vs off with the same normal cfg. APG on default settings. Why is that?

**Comment by Ristellise** [comment]
> I've also been having a bit of issues with APG.
> 
> I noticed the comfy node got updated with some fixes, could you also update this one?
> 
> Also, are we supposed to adjust the normal cfg as well while using apg? Im a bit confused on this. I see 0.001% difference on the results with APG on vs off with the same normal cfg. APG on default settings. Why is that?

There's no need to adjust CFG (It will basically override CFG). Adjust all settings within APG.

**Comment by Ristellise** [comment]
I've 

> Is there any reason why APG would be giving me kind of mushy washed-out images?
> 
> APG	No APG
> CFG: 2 Scale: 2 Momentum: -0.05 Threshold: 3 Eta: 1
> 
> Tried it on `main` and `dev_upstream` with two different XL checkpoints. Reset my configs to a fresh one from reForge, but overall can't seem to get APG working like in the sample.

> XL Models

So I finally tested some XL models and yeah I'm getting similar to exact results. For SD 1.5 Models though (I used aing fro the 2 demonstrated images), there's a difference which I would consider significant.

**Pull request merged**
